 const assetInfo ={
            symbol,
            name,
            instrumentName:symbol,
            isOption,
            isCall,
            quantityOfTrades,
            lastTradedTime,
            isPut,
            isETF: isETF(symbol),
            strikePrice,
            optionDetails,
            vol: parseStringToNumber(cells[4].querySelector('div').innerHTML),
            beforeTodayPrice: convertStringToInt(cells[5].innerHTML),
            last: convertStringToInt(cells[7].innerHTML),
            close: convertStringToInt(cells[10].innerHTML),
            bestBuyQ: convertStringToInt(cells[18].querySelector('div').innerHTML),
            bestBuy: convertStringToInt(cells[19].innerHTML),
            bestSell: convertStringToInt(cells[20].innerHTML),
            bestSellQ: convertStringToInt(cells[21].querySelector('div').innerHTML)
        }